### PR TITLE
Stereo Support

### PR DESCRIPTION
**Pull request by kneave**
I added support for the stereo_mode option in the python script.

### CODE REVIEW

**Comment by ccrisan** [comment]
Thanks!

**Comment by FraBle** [comment]
Looks like picamera doesn't like this 😧

```bash
root@gugelhupf-agent-1:~# raspimjpeg.py -w 640 -h 480 -r 15
2021-04-07 18:12:46:  INFO: raspimjpeg.py 0.8
2021-04-07 18:12:46:  INFO: hello!
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/picamera/camera.py", line 423, in __init__
    stereo_mode = self.STEREO_MODES[stereo_mode]
KeyError: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/raspimjpeg.py", line 330, in <module>
    init_camera()
  File "/usr/local/bin/raspimjpeg.py", line 226, in init_camera
    camera = picamera.PiCamera(resolution=(options.width, options.height), stereo_mode=options.stereo_mode)
  File "/usr/local/lib/python3.7/dist-packages/picamera/camera.py", line 425, in __init__
    raise PiCameraValueError('Invalid stereo mode: %s' % stereo_mode)
picamera.exc.PiCameraValueError: Invalid stereo mode: None
root@gugelhupf-agent-1:~# pip list
Package    Version
---------- -------
picamera   1.13
pip        21.0.1
setuptools 54.2.0
wheel      0.36.2
```

**Comment by FraBle** [comment]
I think [this](https://github.com/ccrisan/streameye/blob/master/extras/raspimjpeg.py#L75) should be `default='none'` instead of `default=None`.

Calling it like this works:
```bash
raspimjpeg.py -w 640 -h 480 -r 15 --stereo none
```

**Comment by kneave** [comment]
You're right, it should be 'none' and apologies for that! You've beaten me to a PR too :)

**Comment by FraBle** [comment]
@kneave haha, no worries, was first wondering if I'm doing anything wrong 😅

**Pull request merged**
